### ISSUE TITLE
Crash immediately upon clicking of 'Refresh' (MacOS)

### ISSUE THREAD

**Issue by Da-Dragon** [Willy-JL/F95Checker#74]
Chances are, I just did something wrong, but alas. This is on MacOS 13.2.1 .
Attempting to refresh launches a new instance of the app, which immediately crashes with the following report:
Messing about with the Refresh settings didn't help.
```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               F95Checker [1561]
Path:                  /Users/USER/Desktop/*/F95Checker.app/Contents/MacOS/F95Checker
Identifier:            io.github.willy-jl.f95checker
Version:               10.2
Code Type:             X86-64 (Translated)
Parent Process:        F95Checker [1086]
Responsible:           F95Checker [1085]
User ID:               501

Date/Time:             2023-04-08 11:41:33.8481 +0200
OS Version:            macOS 13.2.1 (22D68)
Report Version:        12
Anonymous UUID:        90662CB5-2A27-96C4-B909-5084ED2F985B


Time Awake Since Boot: 540 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
abort() called


Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   ???                           	    0x7ff89d84a9a8 ???
1   libsystem_kernel.dylib        	    0x7ff80e4ad22a __pthread_kill + 10
2   libsystem_pthread.dylib       	    0x7ff80e4e4f7b pthread_kill + 263
3   libsystem_c.dylib             	    0x7ff80e42eca5 abort + 123
4   QtCore                        	       0x10ed288f9 qAbort() + 9
5   QtCore                        	       0x10ed2c6a9 0x10ed1e000 + 59049
6   QtCore                        	       0x10f08cc1a QMessageLogger::fatal(char const*, ...) const + 172
7   QtWebEngineCore               	       0x1217aec57 0x1216cd000 + 924759
8   QtWebEngineCore               	       0x1217ac7ad 0x1216cd000 + 915373
9   QtWebEngineCore               	       0x121724852 0x1216cd000 + 358482
10  QtWebEngineCore               	       0x12522f300 0x1216cd000 + 62268160
11  QtWebEngineCore               	       0x1217a9945 0x1216cd000 + 903493
12  QtWebEngineCore               	       0x1217a6c35 0x1216cd000 + 891957
13  QtWebEngineCore               	       0x1217617a3 QtWebEngineCore::ProfileAdapter::ProfileAdapter(QString const&) + 291
14  QtWebEngineCore               	       0x1216fb5d4 QWebEngineProfile::QWebEngineProfile(QObject*) + 84
15  QtWebEngineCore.abi3.so       	       0x10e498ea6 init_type_QWebEngineProfile(_sipSimpleWrapper*, _object*, _object*, _object**, _object**, _object**) + 134
16  sip.cpython-310-darwin.so     	       0x10dfbdb09 sipSimpleWrapper_init + 505
17  F95Checker                    	       0x1048078a2 type_call + 322
18  F95Checker                    	       0x10477e494 _PyObject_MakeTpCall + 132
19  F95Checker                    	       0x1048b927d call_function + 365
20  F95Checker                    	       0x1048b090f _PyEval_EvalFrameDefault + 27983
21  F95Checker                    	       0x1048a84bf _PyEval_Vector + 383
22  F95Checker                    	       0x10477f039 PyVectorcall_Call + 169
23  F95Checker                    	       0x1048aeceb _PyEval_EvalFrameDefault + 20779
24  F95Checker                    	       0x1048a84bf _PyEval_Vector + 383
25  F95Checker                    	       0x10477f039 PyVectorcall_Call + 169
26  F95Checker                    	       0x1048aeceb _PyEval_EvalFrameDefault + 20779
27  F95Checker                    	       0x1048a84bf _PyEval_Vector + 383
28  F95Checker                    	       0x1048a2d43 builtin_exec + 371
29  F95Checker                    	       0x1047e6e96 cfunction_vectorcall_FASTCALL + 86
30  F95Checker                    	       0x1048b91bf call_function + 175
31  F95Checker                    	       0x1048ae61b _PyEval_EvalFrameDefault + 19035
32  F95Checker                    	       0x1048a84bf _PyEval_Vector + 383
33  F95Checker                    	       0x1048b91bf call_function + 175
34  F95Checker                    	       0x1048b090f _PyEval_EvalFrameDefault + 27983
35  F95Checker                    	       0x1048a84bf _PyEval_Vector + 383
36  F95Checker                    	       0x10477f4c9 PyObject_CallObject + 105
37  F95Checker                    	       0x1046fabe7 main + 1063
38  dyld                          	       0x204f72310 start + 2432

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffbdb614 0x7ff7ffbd7000 + 17940
1   runtime                       	    0x7ff7ffbe7530 0x7ff7ffbd7000 + 66864
2   runtime                       	    0x7ff7ffbe8f30 0x7ff7ffbd7000 + 73520

Thread 2:
0   runtime                       	    0x7ff7ffbf987c 0x7ff7ffbd7000 + 141436

Thread 3:
0   runtime                       	    0x7ff7ffbf987c 0x7ff7ffbd7000 + 141436

Thread 4:
0   runtime                       	    0x7ff7ffbf987c 0x7ff7ffbd7000 + 141436

Thread 5:
0   runtime                       	    0x7ff7ffbf987c 0x7ff7ffbd7000 + 141436


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000003  rbp: 0x0000000000000000  rsp: 0x00007ff851b5e598
   r8: 0x00000002050102c0   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x00007ff851b5e590
  r12: 0x0000000000000103  r13: 0x000000012bb55642  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: <unavailable>       rfl: 0x0000000000000283
 tmp0: 0xffffffffffffffff tmp1: 0x00007ff89d84a97c tmp2: 0x00007ff80e4ad220


Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
    0x7ff80e4a5000 -     0x7ff80e4deff7 libsystem_kernel.dylib (*) <87ff381c-4d30-3087-bab7-a5a53d232c00> /usr/lib/system/libsystem_kernel.dylib
    0x7ff80e4df000 -     0x7ff80e4eaff7 libsystem_pthread.dylib (*) <3bd433d4-15bd-3add-a612-95e4d3b20719> /usr/lib/system/libsystem_pthread.dylib
    0x7ff80e3ad000 -     0x7ff80e435fff libsystem_c.dylib (*) <1aec5d1a-6e43-30f9-a9f2-11eb85d3e70c> /usr/lib/system/libsystem_c.dylib
       0x10ed1e000 -        0x10f215fff QtCore (*) <6238782e-d1aa-3245-81ef-2925bf1a4c96> /Users/USER/Desktop/*/F95Checker.app/Contents/MacOS/QtCore
       0x1216cd000 -        0x12bd48fff QtWebEngineCore (*) <473ca65c-6149-3bfa-a88b-95ac735bcd3b> /Users/USER/Desktop/*/F95Checker.app/Contents/MacOS/QtWebEngineCore
       0x10e489000 -        0x10e4bcfff QtWebEngineCore.abi3.so (*) <bbba7cd3-3207-3cce-b34b-1c5d98ea53eb> /Users/USER/Desktop/*/F95Checker.app/Contents/MacOS/lib/PyQt6/QtWebEngineCore.abi3.so
       0x10dfb7000 -        0x10dfcefff sip.cpython-310-darwin.so (*) <f85593b8-68a3-3cfd-8afd-10a823706b39> /Users/USER/Desktop/*/F95Checker.app/Contents/MacOS/lib/PyQt6/sip.cpython-310-darwin.so
       0x1046f8000 -        0x104a63fff io.github.willy-jl.f95checker (*) <54a1a159-52eb-3a3a-a611-396ef8a1204c> /Users/USER/Desktop/*/F95Checker.app/Contents/MacOS/F95Checker
       0x204f6c000 -        0x205003fff dyld (*) <bba77709-6cad-3592-ab03-09d0f7b8610e> /usr/lib/dyld
    0x7ff7ffbd7000 -     0x7ff7ffc06fff runtime (*) <f066db2c-ed38-3f37-8d21-81d15fa908fe> /usr/libexec/rosetta/runtime

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)
Writable regions: Total=1.4G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.4G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
ColorSync                          220K       24 
CoreGraphics                         4K        1 
Kernel Alloc Once                    8K        1 
MALLOC                           228.2M       37 
MALLOC guard page                  192K        9 
MALLOC_MEDIUM (reserved)         600.0M        5         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
Rosetta Arena                     4096K        2 
Rosetta Generic                    812K      200 
Rosetta IndirectBranch             256K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack                80K        8 
Rosetta Thread Context              80K        8 
STACK GUARD                         16K        4 
Stack                             10.1M        5 
Stack Guard                       56.0M        1 
VM_ALLOCATE                       12.6M       62 
VM_ALLOCATE (reserved)              72K        6         reserved VM address space (unallocated)
__CTF                               756        1 
__DATA                            44.5M      649 
__DATA_CONST                      39.5M      383 
__DATA_DIRTY                      1825K      222 
__FONT_DATA                        2352        1 
__GLSLBUILTINS                    5174K        1 
__LINKEDIT                       185.6M       59 
__OBJC_RO                         65.4M        1 
__OBJC_RW                         1987K        2 
__TEXT                           821.8M      646 
dyld private memory                256K        1 
mapped file                        4.5G     1383 
shared memory                     1312K       14 
unshared pmap                     11.8M        8 
===========                     =======  ======= 
TOTAL                              7.1G     3748 
TOTAL, minus reserved VM space     6.1G     3748 



-----------
Full Report
-----------

{"app_name":"F95Checker","timestamp":"2023-04-08 11:41:34.00 +0200","app_version":"","slice_uuid":"54a1a159-52eb-3a3a-a611-396ef8a1204c","build_version":"10.2","platform":1,"bundleID":"io.github.willy-jl.f95checker","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.2.1 (22D68)","roots_installed":0,"name":"F95Checker","incident_id":"7E11096B-374D-46A5-BC5D-A26F860DF8D7"}
{
  "uptime" : 540,
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,3",
  "coalitionID" : 1053,
  "osVersion" : {
    "train" : "macOS 13.2.1",
    "build" : "22D68",
    "releaseType" : "User"
  },
  "captureTime" : "2023-04-08 11:41:33.8481 +0200",
  "incident" : "7E11096B-374D-46A5-BC5D-A26F860DF8D7",
  "pid" : 1561,
  "translated" : true,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-04-08 11:41:33.2893 +0200",
  "procStartAbsTime" : 13057495953,
  "procExitAbsTime" : 13070870522,
  "procName" : "F95Checker",
  "procPath" : "\/Users\/USER\/Desktop\/*\/F95Checker.app\/Contents\/MacOS\/F95Checker",
  "bundleInfo" : {"CFBundleVersion":"10.2","CFBundleIdentifier":"io.github.willy-jl.f95checker"},
  "storeInfo" : {"deviceIdentifierForVendor":"738E79CC-38C9-52DF-A445-C19170C1E5B8","thirdParty":true},
  "parentProc" : "F95Checker",
  "parentPid" : 1086,
  "coalitionName" : "io.github.willy-jl.f95checker",
  "crashReporterKey" : "90662CB5-2A27-96C4-B909-5084ED2F985B",
  "responsiblePid" : 1085,
  "responsibleProc" : "F95Checker",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "asi" : {"libsystem_c.dylib":["abort() called"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":20383,"threadState":{"flavor":"x86_THREAD_STATE","rbp":{"value":0},"r12":{"value":259},"rosetta":{"tmp2":{"value":140703368401440},"tmp1":{"value":140705771334012},"tmp0":{"value":18446744073709551615}},"rbx":{"value":0},"r8":{"value":8673886912,"symbolLocation":0,"symbol":"_main_thread"},"r15":{"value":22},"r10":{"value":0},"rdx":{"value":0},"rdi":{"value":0},"r9":{"value":0},"r13":{"value":5028271682},"rflags":{"value":643},"rax":{"value":0},"rsp":{"value":140704499492248,"symbolLocation":456,"symbol":"__sFX"},"r11":{"value":140704499492240,"symbolLocation":448,"symbol":"__sFX"},"rcx":{"value":0},"r14":{"value":6},"rsi":{"value":3}},"queue":"com.apple.main-thread","frames":[{"imageOffset":140705771334056,"imageIndex":0},{"imageOffset":33322,"symbol":"__pthread_kill","symbolLocation":10,"imageIndex":1},{"imageOffset":24443,"symbol":"pthread_kill","symbolLocation":263,"imageIndex":2},{"imageOffset":531621,"symbol":"abort","symbolLocation":123,"imageIndex":3},{"imageOffset":43257,"symbol":"qAbort()","symbolLocation":9,"imageIndex":4},{"imageOffset":59049,"imageIndex":4},{"imageOffset":3599386,"symbol":"QMessageLogger::fatal(char const*, ...) const","symbolLocation":172,"imageIndex":4},{"imageOffset":924759,"imageIndex":5},{"imageOffset":915373,"imageIndex":5},{"imageOffset":358482,"imageIndex":5},{"imageOffset":62268160,"imageIndex":5},{"imageOffset":903493,"imageIndex":5},{"imageOffset":891957,"imageIndex":5},{"imageOffset":608163,"symbol":"QtWebEngineCore::ProfileAdapter::ProfileAdapter(QString const&)","symbolLocation":291,"imageIndex":5},{"imageOffset":189908,"symbol":"QWebEngineProfile::QWebEngineProfile(QObject*)","symbolLocation":84,"imageIndex":5},{"imageOffset":65190,"symbol":"init_type_QWebEngineProfile(_sipSimpleWrapper*, _object*, _object*, _object**, _object**, _object**)","symbolLocation":134,"imageIndex":6},{"imageOffset":27401,"symbol":"sipSimpleWrapper_init","symbolLocation":505,"imageIndex":7},{"imageOffset":1112226,"symbol":"type_call","symbolLocation":322,"imageIndex":8},{"imageOffset":550036,"symbol":"_PyObject_MakeTpCall","symbolLocation":132,"imageIndex":8},{"imageOffset":1839741,"symbol":"call_function","symbolLocation":365,"imageIndex":8},{"imageOffset":1804559,"symbol":"_PyEval_EvalFrameDefault","symbolLocation":27983,"imageIndex":8},{"imageOffset":1770687,"symbol":"_PyEval_Vector","symbolLocation":383,"imageIndex":8},{"imageOffset":553017,"symbol":"PyVectorcall_Call","symbolLocation":169,"imageIndex":8},{"imageOffset":1797355,"symbol":"_PyEval_EvalFrameDefault","symbolLocation":20779,"imageIndex":8},{"imageOffset":1770687,"symbol":"_PyEval_Vector","symbolLocation":383,"imageIndex":8},{"imageOffset":553017,"symbol":"PyVectorcall_Call","symbolLocation":169,"imageIndex":8},{"imageOffset":1797355,"symbol":"_PyEval_EvalFrameDefault","symbolLocation":20779,"imageIndex":8},{"imageOffset":1770687,"symbol":"_PyEval_Vector","symbolLocation":383,"imageIndex":8},{"imageOffset":1748291,"symbol":"builtin_exec","symbolLocation":371,"imageIndex":8},{"imageOffset":978582,"symbol":"cfunction_vectorcall_FASTCALL","symbolLocation":86,"imageIndex":8},{"imageOffset":1839551,"symbol":"call_function","symbolLocation":175,"imageIndex":8},{"imageOffset":1795611,"symbol":"_PyEval_EvalFrameDefault","symbolLocation":19035,"imageIndex":8},{"imageOffset":1770687,"symbol":"_PyEval_Vector","symbolLocation":383,"imageIndex":8},{"imageOffset":1839551,"symbol":"call_function","symbolLocation":175,"imageIndex":8},{"imageOffset":1804559,"symbol":"_PyEval_EvalFrameDefault","symbolLocation":27983,"imageIndex":8},{"imageOffset":1770687,"symbol":"_PyEval_Vector","symbolLocation":383,"imageIndex":8},{"imageOffset":554185,"symbol":"PyObject_CallObject","symbolLocation":105,"imageIndex":8},{"imageOffset":11239,"symbol":"main","symbolLocation":1063,"imageIndex":8},{"imageOffset":25360,"symbol":"start","symbolLocation":2432,"imageIndex":9}]},{"id":20384,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":17940,"imageIndex":10},{"imageOffset":66864,"imageIndex":10},{"imageOffset":73520,"imageIndex":10}]},{"id":20385,"frames":[{"imageOffset":141436,"imageIndex":10}]},{"id":20386,"frames":[{"imageOffset":141436,"imageIndex":10}]},{"id":20399,"frames":[{"imageOffset":141436,"imageIndex":10}]},{"id":20400,"frames":[{"imageOffset":141436,"imageIndex":10}]}],
  "usedImages" : [
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703368368128,
    "size" : 237560,
    "uuid" : "87ff381c-4d30-3087-bab7-a5a53d232c00",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703368605696,
    "size" : 49144,
    "uuid" : "3bd433d4-15bd-3add-a612-95e4d3b20719",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703367352320,
    "size" : 561152,
    "uuid" : "1aec5d1a-6e43-30f9-a9f2-11eb85d3e70c",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4543602688,
    "size" : 5210112,
    "uuid" : "6238782e-d1aa-3245-81ef-2925bf1a4c96",
    "path" : "\/Users\/USER\/Desktop\/*\/F95Checker.app\/Contents\/MacOS\/QtCore",
    "name" : "QtCore"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4855746560,
    "size" : 174571520,
    "uuid" : "473ca65c-6149-3bfa-a88b-95ac735bcd3b",
    "path" : "\/Users\/USER\/Desktop\/*\/F95Checker.app\/Contents\/MacOS\/QtWebEngineCore",
    "name" : "QtWebEngineCore"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4534603776,
    "size" : 212992,
    "uuid" : "bbba7cd3-3207-3cce-b34b-1c5d98ea53eb",
    "path" : "\/Users\/USER\/Desktop\/*\/F95Checker.app\/Contents\/MacOS\/lib\/PyQt6\/QtWebEngineCore.abi3.so",
    "name" : "QtWebEngineCore.abi3.so"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4529549312,
    "size" : 98304,
    "uuid" : "f85593b8-68a3-3cfd-8afd-10a823706b39",
    "path" : "\/Users\/USER\/Desktop\/*\/F95Checker.app\/Contents\/MacOS\/lib\/PyQt6\/sip.cpython-310-darwin.so",
    "name" : "sip.cpython-310-darwin.so"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4369383424,
    "CFBundleIdentifier" : "io.github.willy-jl.f95checker",
    "size" : 3588096,
    "uuid" : "54a1a159-52eb-3a3a-a611-396ef8a1204c",
    "path" : "\/Users\/USER\/Desktop\/*\/F95Checker.app\/Contents\/MacOS\/F95Checker",
    "name" : "F95Checker",
    "CFBundleVersion" : "10.2"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8673214464,
    "size" : 622592,
    "uuid" : "bba77709-6cad-3592-ab03-09d0f7b8610e",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703124254720,
    "size" : 196608,
    "uuid" : "f066db2c-ed38-3f37-8d21-81d15fa908fe",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  }
],
  "sharedCache" : {
  "base" : 140703364644864,
  "size" : 21474836480,
  "uuid" : "4ca2b729-8206-3c63-badd-faa0225ab773"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=1.4G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.4G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nColorSync                          220K       24 \nCoreGraphics                         4K        1 \nKernel Alloc Once                    8K        1 \nMALLOC                           228.2M       37 \nMALLOC guard page                  192K        9 \nMALLOC_MEDIUM (reserved)         600.0M        5         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nRosetta Arena                     4096K        2 \nRosetta Generic                    812K      200 \nRosetta IndirectBranch             256K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack                80K        8 \nRosetta Thread Context              80K        8 \nSTACK GUARD                         16K        4 \nStack                             10.1M        5 \nStack Guard                       56.0M        1 \nVM_ALLOCATE                       12.6M       62 \nVM_ALLOCATE (reserved)              72K        6         reserved VM address space (unallocated)\n__CTF                               756        1 \n__DATA                            44.5M      649 \n__DATA_CONST                      39.5M      383 \n__DATA_DIRTY                      1825K      222 \n__FONT_DATA                        2352        1 \n__GLSLBUILTINS                    5174K        1 \n__LINKEDIT                       185.6M       59 \n__OBJC_RO                         65.4M        1 \n__OBJC_RW                         1987K        2 \n__TEXT                           821.8M      646 \ndyld private memory                256K        1 \nmapped file                        4.5G     1383 \nshared memory                     1312K       14 \nunshared pmap                     11.8M        8 \n===========                     =======  ======= \nTOTAL                              7.1G     3748 \nTOTAL, minus reserved VM space     6.1G     3748 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "63582c5f8a53461413999550",
      "factorPackIds" : {

      },
      "deploymentId" : 240000002
    },
    {
      "rolloutId" : "61fd92db295c182621ececc3",
      "factorPackIds" : {
        "SIRI_DIALOG_ASSETS" : "63f8d3777a214850f5842941"
      },
      "deploymentId" : 240000346
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "c28e4ee6-1b08-4f90-8e05-2809e78310a3",
      "experimentId" : "6317d2003d24842ff850182a",
      "deploymentId" : 400000013
    }
  ]
}
}

```

**Comment by Willy-JL** [comment]
something is clearly going wrong with the web engine on macos, but i dont have a macos machine to test on, nor the slightest clue as to what the issue is...

**Comment by Willy-JL** [comment]
can you try with one of the latest builds from the actions tab? cx_Freeze was bumped with many improvements to Qt bundling so this might be fixed. also codesign broke so i disabled it for now (and id like to keep it disabled if the app is still runnable), can you check whether it can be run, if it runs properly, and what workarounds are needed? thanks

**Comment by yohudood** [comment]
i dont have macos but is can make a vm for testing

**Comment by Willy-JL** [comment]
thats what i tried to do in the past, its not a good idea mate

**Comment by Da-Dragon** [comment]
> can you try with one of the latest builds from the actions tab? cx_Freeze was bumped with many improvements to Qt bundling so this might be fixed. also codesign broke so i disabled it for now (and id like to keep it disabled if the app is still runnable), can you check whether it can be run, if it runs properly, and what workarounds are needed? thanks

I’m a bit between places at the moment, but I’ll do my best. I’ll let you know if it fixes things.

**Comment by Da-Dragon** [comment]
A thought I had just now:

It seems to be Rosetta related? The crash log seems to mention Rosetta, I don’t think it does that when it’s not running. So it might be a bug that only apple silicon users will experience, though I can’t test that.

**Comment by yohudood** [comment]
https://www.sysprobs.com/macos-13-ventura-vmware-pre-installed-image-download-windows-11-10

**Comment by Da-Dragon** [comment]
I mean, it's a slightly different issue I'm having now!
(In that it just doesn't open at all, for me)

`-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               F95Checker [94161]
Path:                  /private/var/folders/*/F95Checker.app/Contents/MacOS/F95Checker
Identifier:            io.github.willy-jl.f95checker
Version:               10.3
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-08-07 20:25:57.4392 -0400
OS Version:            macOS 13.4 (22F66)
Report Version:        12
Anonymous UUID:        90662CB5-2A27-96C4-B909-5084ED2F985B

Sleep/Wake UUID:       BEA49929-1405-45E8-8A73-8C8B678AA234

Time Awake Since Boot: 1700000 seconds
Time Since Wake:       454 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @executable_path/lib/Python
Referenced from: <815E93F8-3EA3-35A3-93FF-14E0DE82D34C> /private/var/folders/*/F95Checker.app/Contents/MacOS/F95Checker
Reason: tried: '/private/var/folders/98/mssq0rcd1n3btcw_9yr0x4xm0000gn/T/AppTranslocation/DA47D34D-AEFE-41C3-AB60-3CB20A81EE24/d/F95Checker.app/Contents/MacOS/lib/Python' (code signature invalid in <514EFC82-C424-3863-84A8-E24FFD50343D> '/private/var/folders/98/mssq0rcd1n3btcw_9yr0x4xm0000gn/T/AppTranslocation/DA47D34D-AEFE-41C3-AB60-3CB20A81EE24/d/F95Checker.app/Contents/MacOS/lib/Python' (errno=1) sliceOffset=0x00004000, codeBlobOffset=0x006B3FD0, codeBlobSize=0x0001A7B0), '/usr/local/lib/Python' (no such file), '/usr/lib/Python' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   Rosetta Runtime Routines	       0x102ebd9a8 ???
1   <translation info unavailable>	       0x102f44014 ???
2   dyld                          	       0x20317bfd7 abort_with_payload_wrapper_internal + 82
3   dyld                          	       0x20317c009 abort_with_payload + 9
4   dyld                          	       0x2031008f0 dyld4::halt(char const*) + 375
5   dyld                          	       0x2030fdb71 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4526
6   dyld                          	       0x2030fc3bd start + 1805

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffc0c694 0x7ff7ffc08000 + 18068


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000030a092850   x3: 0x00000000000000ca
    x4: 0x000000030a092450   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000002090e69d88
    x8: 0x000000030a092450   x9: 0x0000000000000000  x10: 0x00000000000000ca  x11: 0x000000030a092450
   x12: 0x00000000000000ca  x13: 0x000000030a092850  x14: 0x0000000000000001  x15: 0x0000000000000006
   x16: 0x0000000000000209  x17: 0x0000000000000000  x18: 0x800000010af22b80  x19: 0x0000000102eb3000
   x20: 0x00000000000007ff  x21: 0x000000010af27fa0  x22: 0xffffffffffffffff  x23: 0x0000000102ebd97c
   x24: 0x000000020317bfd7  x25: 0x0000000102ebd248  x26: 0x0000000102f42c70  x27: 0x0000000000000000
   x28: 0x0000000203161c42   fp: 0x000000002c000000   lr: 0x0000000102f44014
    sp: 0x000000010af22b80   pc: 0x0000000102ebd9a8 cpsr: 0x80001000
   far: 0x0000000102f44000  esr: 0x56000080  Address size fault

Binary Images:
       0x2030f6000 -        0x203191fff dyld (*) <9e98a840-a3ac-31c1-ab97-829af9bd6864> /usr/lib/dyld
    0x7ff7ffc08000 -     0x7ff7ffc37fff runtime (*) <c4d322c3-30c5-3c52-adb8-2fd12ec92bc0> /usr/libexec/rosetta/runtime
       0x10aebd000 -        0x10af10fff libRosettaRuntime (*) <c8f25cdc-b334-3f67-bc30-50e9852f8da2> /Library/Apple/*/libRosettaRuntime
       0x102e9e000 -        0x102ea1fff io.github.willy-jl.f95checker (*) <815e93f8-3ea3-35a3-93ff-14e0de82d34c> /private/var/folders/*/F95Checker.app/Contents/MacOS/F95Checker
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1548K resident=0K(0%) swapped_out_or_unallocated=1548K(100%)
Writable regions: Total=157.1M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=157.1M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Rosetta Arena                     4096K        2 
Rosetta Generic                    920K      227 
Rosetta IndirectBranch              32K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack                20K        2 
Rosetta Thread Context              20K        2 
Stack                             8176K        1 
Stack Guard                       56.0M        1 
VM_ALLOCATE                       15.9M        7 
VM_ALLOCATE (reserved)               4K        1         reserved VM address space (unallocated)
__DATA                             112K        5 
__DATA_CONST                        32K        1 
__DATA_DIRTY                        16K        1 
__LINKEDIT                         416K        8 
__TEXT                            1168K        4 
dyld private memory                260K        2 
mapped file                        6.8G       62 
===========                     =======  ======= 
TOTAL                              7.1G      328 
TOTAL, minus reserved VM space     7.1G      328 



-----------
Full Report
-----------

{"app_name":"F95Checker","timestamp":"2023-08-07 20:25:57.00 -0400","app_version":"","slice_uuid":"815e93f8-3ea3-35a3-93ff-14e0de82d34c","build_version":"10.3","platform":1,"bundleID":"io.github.willy-jl.f95checker","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.4 (22F66)","roots_installed":0,"name":"F95Checker","incident_id":"039E7FD1-1175-459C-87C5-3340EB7A4987"}
{
  "uptime" : 1700000,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,3",
  "coalitionID" : 229047,
  "osVersion" : {
    "train" : "macOS 13.4",
    "build" : "22F66",
    "releaseType" : "User"
  },
  "captureTime" : "2023-08-07 20:25:57.4392 -0400",
  "incident" : "039E7FD1-1175-459C-87C5-3340EB7A4987",
  "pid" : 94161,
  "translated" : true,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-08-07 20:25:57.3323 -0400",
  "procStartAbsTime" : 41335470794861,
  "procExitAbsTime" : 41335473343227,
  "procName" : "F95Checker",
  "procPath" : "\/private\/var\/folders\/*\/F95Checker.app\/Contents\/MacOS\/F95Checker",
  "bundleInfo" : {"CFBundleVersion":"10.3","CFBundleIdentifier":"io.github.willy-jl.f95checker"},
  "storeInfo" : {"deviceIdentifierForVendor":"738E79CC-38C9-52DF-A445-C19170C1E5B8","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "io.github.willy-jl.f95checker",
  "crashReporterKey" : "90662CB5-2A27-96C4-B909-5084ED2F985B",
  "codeSigningID" : "",
  "codeSigningTeamID" : "",
  "codeSigningValidationCategory" : 0,
  "codeSigningTrustLevel" : 0,
  "wakeTime" : 454,
  "sleepWakeUUID" : "BEA49929-1405-45E8-8A73-8C8B678AA234",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @executable_path\/lib\/Python","Referenced from: <815E93F8-3EA3-35A3-93FF-14E0DE82D34C> \/private\/var\/folders\/*\/F95Checker.app\/Contents\/MacOS\/F95Checker","Reason: tried: '\/private\/var\/folders\/98\/mssq0rcd1n3btcw_9yr0x4xm0000gn\/T\/AppTranslocation\/DA47D34D-AEFE-41C3-AB60-3CB20A81EE24\/d\/F95Checker.app\/Contents\/MacOS\/lib\/Python' (code signature invalid in <514EFC82-C424-3863-84A8-E24FFD50343D> '\/private\/var\/folders\/98\/mssq0rcd1n3btcw_9yr0x4xm0000gn\/T\/AppTranslocation\/DA47D34D-AEFE-41C3-AB60-3CB20A81EE24\/d\/F95Checker.app\/Contents\/MacOS\/lib\/Python' (errno=1) sliceOffset=0x00004000, codeBlobOffset=0x006B3FD0, codeBlobSize=0x0001A7B0), '\/usr\/local\/lib\/Python' (no such file), '\/usr\/lib\/Python' (no such file, not in dyld cache)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":31154405,"threadState":{"x":[{"value":6},{"value":1},{"value":13053274192},{"value":202},{"value":13053273168},{"value":0},{"value":0},{"value":139869986184},{"value":13053273168},{"value":0},{"value":202},{"value":13053273168},{"value":202},{"value":13053274192},{"value":1},{"value":6},{"value":521},{"value":0},{"value":9223372041333386112},{"value":4343934976},{"value":2047},{"value":4478631840},{"value":18446744073709551615},{"value":4343978364},{"value":8641822679,"symbolLocation":82,"symbol":"abort_with_payload_wrapper_internal"},{"value":4343976520},{"value":4344523888},{"value":0},{"value":8641715266,"symbolLocation":10,"symbol":"__abort_with_payload"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4344528916},"cpsr":{"value":2147487744},"fp":{"value":738197504},"sp":{"value":4478610304},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":4343978408,"matchesCrashFrame":1},"far":{"value":4344528896}},"frames":[{"imageOffset":4343978408,"region":"Rosetta Runtime Routines","symbolLocation":10664,"imageIndex":4},{"imageOffset":4344528916,"region":"<translation info unavailable>","imageIndex":4},{"imageOffset":548823,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":82,"imageIndex":0},{"imageOffset":548873,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":0},{"imageOffset":43248,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":0},{"imageOffset":31601,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4526,"imageIndex":0},{"imageOffset":25533,"symbol":"start","symbolLocation":1805,"imageIndex":0}]},{"id":31154417,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":18068,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8641273856,
    "size" : 638976,
    "uuid" : "9e98a840-a3ac-31c1-ab97-829af9bd6864",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703124455424,
    "size" : 196608,
    "uuid" : "c4d322c3-30c5-3c52-adb8-2fd12ec92bc0",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4478193664,
    "size" : 344064,
    "uuid" : "c8f25cdc-b334-3f67-bc30-50e9852f8da2",
    "path" : "\/Library\/Apple\/*\/libRosettaRuntime",
    "name" : "libRosettaRuntime"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4343848960,
    "CFBundleIdentifier" : "io.github.willy-jl.f95checker",
    "size" : 16384,
    "uuid" : "815e93f8-3ea3-35a3-93ff-14e0de82d34c",
    "path" : "\/private\/var\/folders\/*\/F95Checker.app\/Contents\/MacOS\/F95Checker",
    "name" : "F95Checker",
    "CFBundleVersion" : "10.3"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 140703411896320,
  "size" : 21474836480,
  "uuid" : "9bdf650c-7fc0-3de1-bac4-8535aea9b6aa"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1548K resident=0K(0%) swapped_out_or_unallocated=1548K(100%)\nWritable regions: Total=157.1M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=157.1M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nRosetta Arena                     4096K        2 \nRosetta Generic                    920K      227 \nRosetta IndirectBranch              32K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack                20K        2 \nRosetta Thread Context              20K        2 \nStack                             8176K        1 \nStack Guard                       56.0M        1 \nVM_ALLOCATE                       15.9M        7 \nVM_ALLOCATE (reserved)               4K        1         reserved VM address space (unallocated)\n__DATA                             112K        5 \n__DATA_CONST                        32K        1 \n__DATA_DIRTY                        16K        1 \n__LINKEDIT                         416K        8 \n__TEXT                            1168K        4 \ndyld private memory                260K        2 \nmapped file                        6.8G       62 \n===========                     =======  ======= \nTOTAL                              7.1G      328 \nTOTAL, minus reserved VM space     7.1G      328 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "af04af58f98514a289573262484090052b599a57",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60f8ddccefea4203d95cbeef",
      "factorPackIds" : {

      },
      "deploymentId" : 240000025
    },
    {
      "rolloutId" : "6425c75e4327780c10cc4252",
      "factorPackIds" : {
        "SIRI_HOME_AUTOMATION_INTENT_SELECTION_CACHE" : "642600a457e7664b1698eb32"
      },
      "deploymentId" : 240000004
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro18,3, BootROM 8422.121.1, proc 10:8:2 processors, 16 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: Color LCD, 3024 x 1964 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Samsung
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Apr  7 2023 15:18:26 version 20.96.28.1.8.7.146 FWID 01-aff1b48a
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.`

**Comment by Willy-JL** [comment]
im assuming this is the same issue that was fixed in #87

**Comment by Da-Dragon** [comment]
@Willy-JL How do I fully uninstall F95 checker? The refresher still crashes for me, even using 10.3 beta 1074. I'm thinking it could be due to artefacts, possibly.
